language: python

python:
  - "2.7"

install:
  - pip install -r requirements.txt --use-mirrors

before_script:
  - cp website/local_settings.travis.py website/local_settings.py
  - psql -c 'create database happyteam;' -U postgres

script:
  - true  # no tests yet